---
title: "p8105_hw6_tw2918"
output: github_document
date: "2023-11-20"
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(modelr)
set.seed(1)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Probelm 1

**Import and Clean Dataset**

* update the victim's first and last name to proper case
* replace `unknown` to missing value `NA`
* update `victim_age` to numeric variable
* create new variable `city_state` and `case_sovled`
* filter out four `city_state` values
* filter and only keep observations if `victim_race` is white or black. 

```{r}
homicide_df = read_csv("./data/homicide_data.csv", show_col_types = FALSE) |>
  janitor::clean_names()|>
  mutate (
    victim_last = str_to_title(victim_last),
    victim_first = str_to_title(victim_first),
    across(c(uid, victim_last, victim_first, victim_race, victim_age, victim_sex, city, state, disposition), ~na_if(., "Unknown")),
    victim_age = as.numeric(victim_age),
    city_state = paste(city, state, sep = ", "),
    case_solved = ifelse(grepl("Closed", disposition, ignore.case = TRUE), "Yes", "No")
    )|>
  filter(
    !city_state %in% c("Tulsa, AL", "Dallas, TX", "Phoenix, AZ", "Kansas City, MO" ),
    victim_race == "White" | victim_race == "Black"
    )
```

